// Regenerates migrations/0002_seed_prompts.sql from data/prompts.csv.
// Edit the CSV (it opens in Excel), run `npm run seed:gen`, redeploy the seed.
import fs from "node:fs";

function parseCsv(text) {
  const rows = [];
  let row = [], field = "", quoted = false;
  for (let i = 0; i < text.length; i++) {
    const c = text[i];
    if (quoted) {
      if (c === '"') {
        if (text[i + 1] === '"') { field += '"'; i++; } else quoted = false;
      } else field += c;
    } else if (c === '"') quoted = true;
    else if (c === ",") { row.push(field); field = ""; }
    else if (c === "\n") { row.push(field); rows.push(row); row = []; field = ""; }
    else if (c !== "\r") field += c;
  }
  if (field.length || row.length) { row.push(field); rows.push(row); }
  return rows;
}

const q = (s) => "'" + String(s).replace(/'/g, "''") + "'";

const rows = parseCsv(fs.readFileSync("data/prompts.csv", "utf8"));
const header = rows.shift().map((h) => h.trim());
const idx = Object.fromEntries(header.map((h, i) => [h, i]));
const records = rows.filter((r) => r.length > 1 && r[idx.id]);

// Series colors are a fixed categorical order validated for colour-vision
// deficiency against the ICRON supporting palette. They are deliberately not the
// competitors' own brand colours: three real logos are blue, which would collide
// with ICRON blue and with each other.
const brands = [
  { id: "icron",       label: "ICRON",       is_self: 1, color: "#435AEE", sort_order: 0,
    aliases: [{ pattern: "ICRON", caseSensitive: false }, { pattern: "icrontech", caseSensitive: false }] },
  { id: "kinaxis",     label: "Kinaxis",     is_self: 0, color: "#0B9A83", sort_order: 10,
    aliases: [{ pattern: "Kinaxis", caseSensitive: false }, { pattern: "RapidResponse", caseSensitive: false }, { pattern: "Rapid Response", caseSensitive: false }] },
  { id: "blueyonder",  label: "Blue Yonder", is_self: 0, color: "#B4671B", sort_order: 20,
    aliases: [{ pattern: "Blue ?Yonder", caseSensitive: false }, { pattern: "JDA Software", caseSensitive: false }, { pattern: "Luminate", caseSensitive: false }] },
  { id: "omp",         label: "OMP",         is_self: 0, color: "#971CB2", sort_order: 30,
    aliases: [{ pattern: "OMP", caseSensitive: true }, { pattern: "Unison Planning", caseSensitive: false }] },
  { id: "sap",         label: "SAP",         is_self: 0, color: "#06980B", sort_order: 40,
    aliases: [{ pattern: "SAP", caseSensitive: true }] },
];

const out = [];
out.push("-- Generated by scripts/gen-seed.mjs. Do not edit by hand; edit data/prompts.csv.");
out.push("DELETE FROM prompts;");
out.push("DELETE FROM brands;");
for (const b of brands) {
  out.push(`INSERT INTO brands (id,label,is_self,aliases,color,sort_order,active) VALUES (${q(b.id)},${q(b.label)},${b.is_self},${q(JSON.stringify(b.aliases))},${q(b.color)},${b.sort_order},1);`);
}
for (const r of records) {
  out.push(
    "INSERT INTO prompts (id,topic,country,language,intent,prompt_native,prompt_en,active) VALUES (" +
    [idx.id, idx.topic, idx.country, idx.language, idx.intent, idx.prompt_native, idx.prompt_en]
      .map((i) => q(r[i].trim())).join(",") + ",1);"
  );
}
fs.writeFileSync("migrations/0002_seed_prompts.sql", out.join("\n") + "\n");
console.log(`Wrote migrations/0002_seed_prompts.sql (${records.length} prompts, ${brands.length} brands)`);
